const canvas=document.getElementById('simCanvas'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id); const inputs=['length','width','wheelbase','frontTrack','rearTrack','bogieSpacing','radius','globalLimit'];
let mode='straight',zoom=1,pan={x:0,y:0},drag=null,running=false,progress=0,manual={FL:0,FR:0,RL:0,RR:0};
const corners=['FL','FR','RL','RR'];
const colors={FL:'#df5f3f',FR:'#df5f3f',RL:'#138a91',RR:'#138a91'};
const wheelNames=corners.flatMap(c=>[c+'1',c+'2']);
function cornerOf(name){return name.slice(0,2)}
function val(id){return Math.max(0.01,parseFloat($(id).value)||0.01)}
function effectiveWheelbase(){return Math.min(val('wheelbase'),val('length'))}
function effectiveBogieSpacing(){return Math.min(val('bogieSpacing'),effectiveWheelbase()*0.6)}
function calculateWheelPositions(){const wb=effectiveWheelbase(),half=effectiveBogieSpacing()/2,cornerPos={FL:{x:wb/2,y:val('frontTrack')/2},FR:{x:wb/2,y:-val('frontTrack')/2},RL:{x:-wb/2,y:val('rearTrack')/2},RR:{x:-wb/2,y:-val('rearTrack')/2}},out={};corners.forEach(c=>{out[c+'1']={x:cornerPos[c].x+half,y:cornerPos[c].y};out[c+'2']={x:cornerPos[c].x-half,y:cornerPos[c].y}});return out}
function calculateICR(){const r=val('radius');if(mode==='straight'||mode==='manual')return{x:Infinity,y:Infinity};return{x:0,y:(mode==='left'?1:-1)*r}}
function angleForWheel(w,icr){if(!Number.isFinite(icr.x))return 0;let angle=-Math.atan2(icr.x-w.x,icr.y-w.y)*180/Math.PI;if(angle>90)angle-=180;if(angle<-90)angle+=180;return angle}
function applyAngleLimits(corner,ideal){let min=-val('globalLimit'),max=val('globalLimit');if(!$('globalEnabled').checked){min=parseFloat(document.querySelector(`[data-min="${corner}"]`).value)||-45;max=parseFloat(document.querySelector(`[data-max="${corner}"]`).value)||45}const applied=Math.max(min,Math.min(max,ideal));return{ideal,applied,limited:Math.abs(applied-ideal)>.01}}
function calculateAckermann(){const positions=calculateWheelPositions(),icr=calculateICR(),out={};wheelNames.forEach(name=>{const corner=cornerOf(name);const ideal=mode==='manual'?manual[corner]:angleForWheel(positions[name],icr);const limited=applyAngleLimits(corner,ideal);const dx=positions[name].x-(Number.isFinite(icr.x)?icr.x:0),dy=positions[name].y-(Number.isFinite(icr.y)?icr.y:0);out[name]={...positions[name],...limited,radius:Number.isFinite(icr.x)?Math.hypot(dx,dy):Infinity}});return{positions,out,icr}}
function calculateTrajectory(state){return state}
function checkConstraints(state){return wheelNames.some(n=>state.out[n].limited)}
function resize(){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function worldToScreen(x,y){const scale=Math.min(canvas.clientWidth/(val('length')+12),canvas.clientHeight/(val('width')+12))*zoom;return{x:canvas.clientWidth/2+(x+pan.x)*scale,y:canvas.clientHeight/2-(y+pan.y)*scale}}
function posePoint(x,y,icr){if(!Number.isFinite(icr.x))return{x:x+progress*val('length')*2-val('length'),y};const theta=progress*.9*(icr.y>=0?1:-1);const dx=x-icr.x,dy=y-icr.y;return{x:icr.x+dx*Math.cos(theta)-dy*Math.sin(theta),y:icr.y+dx*Math.sin(theta)+dy*Math.cos(theta)}}
function drawGrid(scale){ctx.strokeStyle='#d4d5ce';ctx.lineWidth=1;const step=scale;for(let x=canvas.clientWidth/2%step;x<canvas.clientWidth;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.clientHeight);ctx.stroke()}for(let y=canvas.clientHeight/2%step;y<canvas.clientHeight;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.clientWidth,y);ctx.stroke()}}
function drawArrow(from,to,color='#172027'){ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();const angle=Math.atan2(to.y-from.y,to.x-from.x),size=6;ctx.beginPath();ctx.moveTo(to.x,to.y);ctx.lineTo(to.x-size*Math.cos(angle-.45),to.y-size*Math.sin(angle-.45));ctx.lineTo(to.x-size*Math.cos(angle+.45),to.y-size*Math.sin(angle+.45));ctx.closePath();ctx.fill()}
function drawDimension(a,b,label){ctx.strokeStyle='#7a8585';ctx.fillStyle='#536064';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();drawArrow(a,{x:a.x+(b.x-a.x)*.12,y:a.y+(b.y-a.y)*.12},'#7a8585');drawArrow(b,{x:b.x+(a.x-b.x)*.12,y:b.y+(a.y-b.y)*.12},'#7a8585');ctx.font='11px DM Mono';ctx.textAlign='center';ctx.fillText(label,(a.x+b.x)/2,(a.y+b.y)/2-7);ctx.textAlign='start'}
function draw(){const state=calculateTrajectory(calculateAckermann()),scale=Math.min(canvas.clientWidth/(val('length')+12),canvas.clientHeight/(val('width')+12))*zoom;ctx.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);drawGrid(scale);ctx.save();ctx.setLineDash([5,6]);ctx.strokeStyle='#a9aba3';ctx.lineWidth=1;const o=worldToScreen(0,0);ctx.beginPath();ctx.moveTo(0,o.y);ctx.lineTo(canvas.clientWidth,o.y);ctx.moveTo(o.x,0);ctx.lineTo(o.x,canvas.clientHeight);ctx.stroke();ctx.restore();
 const wb=effectiveWheelbase();
 if(Number.isFinite(state.icr.x)){const c=worldToScreen(state.icr.x,state.icr.y);ctx.strokeStyle='#df5f3f';ctx.lineWidth=1.5;ctx.setLineDash([4,4]);ctx.beginPath();ctx.arc(c.x,c.y,val('radius')*scale,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#df5f3f';ctx.beginPath();ctx.arc(c.x,c.y,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#a84731';ctx.font='12px DM Mono';ctx.fillText('ICR',c.x+8,c.y-8);ctx.setLineDash([3,5]);wheelNames.forEach(n=>{const w=state.out[n],p=worldToScreen(w.x,w.y);ctx.strokeStyle=colors[cornerOf(n)]+'40';ctx.lineWidth=1;ctx.beginPath();ctx.arc(c.x,c.y,Math.hypot(c.x-p.x,c.y-p.y),0,Math.PI*2);ctx.stroke()});ctx.setLineDash([])}
 const body=[[-val('length')/2,-val('width')/2],[val('length')/2,-val('width')/2],[val('length')/2,val('width')/2],[-val('length')/2,val('width')/2]].map(([x,y])=>worldToScreen(x,y));ctx.fillStyle='#26343a';ctx.globalAlpha=.09;ctx.beginPath();body.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='#52636a';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle='#df5f3f';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(body[1].x,body[1].y);ctx.lineTo(body[2].x,body[2].y);ctx.stroke();
 [['frontTrack',wb/2],['rearTrack',-wb/2]].forEach(([trackId,x])=>{const a=worldToScreen(x,-val(trackId)/2),b=worldToScreen(x,val(trackId)/2);ctx.strokeStyle='#55646a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()});
 const lengthY=val('width')/2+1.15,widthX=val('length')/2+1.15;drawDimension(worldToScreen(-val('length')/2,lengthY),worldToScreen(val('length')/2,lengthY),`COMPRIMENTO ${val('length').toFixed(2)} m`);drawDimension(worldToScreen(widthX,-val('width')/2),worldToScreen(widthX,val('width')/2),`LARGURA ${val('width').toFixed(2)} m`);ctx.fillStyle='#536064';ctx.font='10px DM Mono';ctx.fillText(`BITOLA F ${val('frontTrack').toFixed(2)} m`,worldToScreen(wb/2,-val('frontTrack')/2-0.35).x,worldToScreen(wb/2,-val('frontTrack')/2-0.35).y);ctx.fillText(`BITOLA T ${val('rearTrack').toFixed(2)} m`,worldToScreen(-wb/2,-val('rearTrack')/2-0.35).x,worldToScreen(-wb/2,-val('rearTrack')/2-0.35).y);
 const bodyTheta=Number.isFinite(state.icr.x)?progress*.9*(state.icr.y>=0?1:-1):0;
 wheelNames.forEach(n=>{const w=state.out[n],corner=cornerOf(n),pose=posePoint(w.x,w.y,state.icr),p=worldToScreen(pose.x,pose.y),len=val('width')*.22*scale/2,heading=-w.applied*Math.PI/180-bodyTheta;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(heading);ctx.fillStyle=colors[corner];ctx.fillRect(-len,-6,len*2,12);ctx.strokeStyle='#172027';ctx.lineWidth=1;ctx.strokeRect(-len,-6,len*2,12);ctx.restore();drawArrow({x:p.x,y:p.y},{x:p.x+Math.cos(heading)*len*1.7,y:p.y+Math.sin(heading)*len*1.7},colors[corner]);const labelDir=n.endsWith('1')?-1:1;ctx.fillStyle='#172027';ctx.font='600 11px Barlow Condensed';ctx.fillText(n,p.x+9,p.y-9*labelDir);ctx.fillStyle=w.limited?'#c3553c':'#536064';ctx.font='500 10px DM Mono';ctx.fillText(`${w.applied.toFixed(2)}°`,p.x+9,p.y-9*labelDir+12*labelDir)})
 if(running){progress=(progress+val('speed')*.002)%1;requestAnimationFrame(()=>draw())}}
function render(){const state=calculateTrajectory(calculateAckermann()),limited=checkConstraints(state);$('icrValue').textContent=Number.isFinite(state.icr.x)?`x ${state.icr.x.toFixed(2)} · y ${state.icr.y.toFixed(2)} m`:'x ∞ · y ∞ m';$('radiusValue').textContent=`${val('radius').toFixed(2)} m`;$('conditionValue').textContent=limited?'ACKERMANN LIMITADO':'ACKERMANN OK';$('conditionValue').className=limited?'warn':'ok';$('statusText').textContent=limited?'ACKERMANN LIMITADO':'ACKERMANN OK';$('statusText').style.color=limited?'var(--warn)':'var(--ok)';$('wheelRows').innerHTML=wheelNames.map(n=>{const w=state.out[n];return `<div class="wheel-row"><strong>${n}</strong><span>${w.x.toFixed(2)} / ${w.y.toFixed(2)} m</span><span class="ideal">${w.ideal.toFixed(2)}°</span><span class="applied">${w.applied.toFixed(2)}°</span><span>${Number.isFinite(w.radius)?w.radius.toFixed(2)+' m':'∞'}</span><span class="status ${w.limited?'limited':''}">${w.limited?'LIMITADO':'OK'}</span></div>`}).join('');draw()}
function createLimits(){ $('limits').innerHTML=corners.map(n=>`<div class="limit-row"><strong>${n}</strong><input type="number" data-min="${n}" value="-45" aria-label="mínimo ${n}"><input type="number" data-max="${n}" value="45" aria-label="máximo ${n}"></div>`).join('');}
function createManual(){ $('manualControls').innerHTML=corners.map(n=>`<div class="manual-row"><b>${n}</b><input data-manual="${n}" type="range" min="-89" max="89" value="0"><output id="manual-${n}">0°</output></div>`).join('');document.querySelectorAll('[data-manual]').forEach(i=>i.oninput=()=>{manual[i.dataset.manual]=+i.value;$(`manual-${i.dataset.manual}`).textContent=`${i.value}°`;render()})}
inputs.forEach(id=>$(id).addEventListener('input',render));document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelector('.mode.active').classList.remove('active');b.classList.add('active');mode=b.dataset.mode;$('manualControls').classList.toggle('visible',mode==='manual');render()});$('globalEnabled').onchange=render;$('start').onclick=()=>{running=true;draw()};$('pause').onclick=()=>running=false;$('reset').onclick=()=>{running=false;progress=0;pan={x:0,y:0};zoom=1;render()};$('speed').oninput=()=>{$('speedValue').textContent=`${(+$('speed').value).toFixed(1)} m/s`};$('zoomIn').onclick=()=>{zoom=Math.min(3,zoom+.1);$('zoomValue').textContent=`${Math.round(zoom*100)}%`;draw()};$('zoomOut').onclick=()=>{zoom=Math.max(.4,zoom-.1);$('zoomValue').textContent=`${Math.round(zoom*100)}%`;draw()};$('fit').onclick=()=>{zoom=1;pan={x:0,y:0};$('zoomValue').textContent='100%';draw()};canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.4,Math.min(3,zoom+(e.deltaY<0?.1:-.1)));$('zoomValue').textContent=`${Math.round(zoom*100)}%`;draw()};canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(drag){const scale=Math.min(canvas.clientWidth/(val('length')+12),canvas.clientHeight/(val('width')+12))*zoom;pan.x+=(e.clientX-drag.x)/scale;pan.y-=(e.clientY-drag.y)/scale;drag={x:e.clientX,y:e.clientY};draw()}};canvas.onpointerup=()=>drag=null;
createLimits();createManual();$('resetConfig').onclick=()=>{[['length',14],['width',6],['wheelbase',8],['frontTrack',4],['rearTrack',4],['bogieSpacing',1.2],['radius',20],['globalLimit',30]].forEach(([id,value])=>$(id).value=value);$('globalEnabled').checked=false;document.querySelectorAll('[data-min]').forEach(input=>input.value=-45);document.querySelectorAll('[data-max]').forEach(input=>input.value=45);document.querySelector('.mode.active').classList.remove('active');document.querySelector('[data-mode="straight"]').classList.add('active');mode='straight';render()};new ResizeObserver(resize).observe(canvas);render();
